### PR TITLE
initialize main project repo

### PR DESCRIPTION
**Pull request by sslivkoff**

### CODE REVIEW

**Comment by fatmai** [comment]
@sslivkoff, confused about this one. can you fill me in. what is "hooks/post_gen_project.sh" ?

**Comment by sslivkoff** [comment]
the `hooks/post_gen_project.sh` script is run immediately after the project is created. you can also do `hooks/post_gen_project.py` for python, or use other file names to hook into other parts of the lifecycle. here are some examples https://github.com/audreyr/cookiecutter-pypackage/tree/master/hooks

this code initializes the project as a repo, which was not happening before

**Comment by fatmai** [comment]
that's neat. I like that. hooks/ should be under {{cookiecutter.project_name}} though, right? also can you then update the README file too.

**Comment by sslivkoff** [comment]
hooks can only be at the top level dir because you don't actually want those files as part of the project

**Comment by sslivkoff** [comment]
update the readme with what?

**Comment by fatmai** [comment]
its part of the new tree?

**Comment by sslivkoff** [comment]
it's 1 level above the project template tree so it's not part of the readme

**Comment by fatmai** [comment]
then I am still confused...

**Comment by fatmai** [comment]
@sslivkoff thanks for the explanation. merging :)

**Pull request merged**
