### PR TITLE
removed project_repo_name as cookiecutter field. project_repo_name im…

### PR DESCRIPTION
**Pull request by sslivkoff**
…plies the name of the entire project repo, but project_name already fills that role

### CODE REVIEW

**Comment by fatmai** [comment]
I have conflicting opinions about this one actually. 

1) project_name can be a "longer" identifier that is more understandable when we talk about a project: e.g. visual attention

2) project_repo_name however could be a short version so typing and referring to it is easier. e.g. visat

dunno, @r-b-g-b, @sslivkoff what do you think?

**Comment by sslivkoff** [comment]
I am not opposed to making that an option. However, right now there are no references to `{{ cookiecutter.project_repo_name }}` in any of the jinja templates, and the cookiecutter variables are not saved anywhere after project initialization, so it is currently a redundant parameter.

Which specific files do you think might distinguish between `{{ cookiecutter.project_name }}` and `{{ cookiecutter.project_repo_name }}` in their templates?

**Comment by fatmai** [comment]
the more I think about this, actually, the high-level directory should probably be the project_repo_name, and project_name will only be used in README's or other descriptive stuff. 

{{cookiecutter.project_name}} --> {{cookiecutter.project_repo_name}}

what do you think?

**Comment by sslivkoff** [comment]
that sounds good to me

**Comment by fatmai** [comment]
closing this w/o merging. #17 will make the new change.

**Pull request closed without merging**
