### PR TITLE
added template for preprocessed metadata

### PR DESCRIPTION
**Pull request by r-b-g-b**

### CODE REVIEW

**Comment by fatmai** [comment]
@r-b-g-b I can merge this if you agree with the new changes.

**Comment by r-b-g-b** [comment]
Looks good to me!

**Comment by sslivkoff** [comment]
I think this looks really good

**Comment by sslivkoff** [comment]
Chances are people will need to adapt the loader function in load.py to their needs with like clipping, special reordering, etc. It would be really hard to capture all forms of variance in a consistent json api, so those sorts of details should go into load.py or a parms.py

**Comment by fatmai** [comment]
yes. these json files are meant to be pointers to the data. so yeah, details should be in the scripts.

**Pull request merged**
